services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:8883"
      - "8084:8084"
    volumes:
      - ./apps/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./apps/mqtt/keys:/mosquitto/certs
      - ./apps/mqtt/passwd:/mosquitto/passwd
      - /etc/letsencrypt/archive/pp.mattymo.dev:/etc/letsencrypt/archive/pp.mattymo.dev:ro

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      mqttnet:
        aliases:
          - pp.mattymo.dev

  mqtt-listener:
    image: posture-pad-mqtt-listener:latest
    container_name: mqtt-listener
    init: true
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - MQTT_PWD=${MQTT_PWD}
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - mqttnet
    develop:
      watch:
        - action: sync+restart
          path: ./apps/mqtt/dist/listener.js
          target: /app/listener.js
          initial_sync: true

networks:
  mqttnet:
