services:
  # The MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./certs:/mosquitto/certs
      - ./passwd:/mosquitto/passwd
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Node.js App
  mqtt-listener:
    image: posture-pad-mqtt-listener:latest
    container_name: mqtt-listener
    init: true
    restart: unless-stopped
    depends_on:
      - mosquitto
    environment:
      # Use the service name "mosquitto" as the hostname
      - BROKER_URL=mqtts://mosquitto:8883
      - DATABASE_URL=${DATABASE_URL}
      - MQTT_PWD=${MQTT_PWD}
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

