# Listen on the standard MQTT port
listener 8883
protocol mqtt

listener 8084
protocol websockets

certfile /mosquitto/certs/fullchain.pem
keyfile /mosquitto/certs/privkey.pem

password_file /mosquitto/passwd
allow_anonymous false
require_certificate false
